### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iceguru** [bahamapascal/IOTA-Balanace-Checker#2]
`ubuntu@ubuntu:~/Downloads/IOTA-Balanace-Checker-master$ py BalanceChecker.py
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    BalanceChecker.py
NameError: name 'BalanceChecker' is not defined
`

**Comment by iceguru** [comment]
https://stackoverflow.com/questions/21122540/input-error-nameerror-name-is-not-defined

**Comment by iceguru** [comment]
ubuntu@ubuntu:~/Downloads/IOTA-Balanace-Checker-master$ python --version
Python 2.7.14

Although I do have 3 installed? ...not sure what's going on.

**Comment by iceguru** [comment]
Segmentation fault (core dumped)

is at the end of the file when I try to install dependencies.

**Comment by bahamapascal** [comment]
Apparently your system variable is pointing to Python 2.7
But the script should work with both Python 2.x and Python 3.x
Did you install the dependencies with `pip install -r requirements.txt`

**Comment by iceguru** [comment]
Yes and no ...

`ubuntu@ubuntu:~/Downloads/IOTA-Balanace-Checker-master$ pip install -r requirements.txt 
Collecting pyota (from -r requirements.txt (line 1))
  Using cached PyOTA-2.0.2-py2.py3-none-any.whl
Collecting six (from -r requirements.txt (line 2))
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pysha3 (from pyota->-r requirements.txt (line 1))
  Using cached pysha3-1.0.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting typing; python_version < "3.0" (from pyota->-r requirements.txt (line 1))
  Using cached typing-3.6.2-py2-none-any.whl
Collecting requests[security]>=2.4.1 (from pyota->-r requirements.txt (line 1))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting filters (from pyota->-r requirements.txt (line 1))
  Using cached filters-1.3.2-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting cryptography>=1.3.4; extra == "security" (from requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached cryptography-2.1.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached pyOpenSSL-17.5.0-py2.py3-none-any.whl
Collecting py2casefold; python_version < "3.0" (from filters->pyota->-r requirements.txt (line 1))
  Using cached py2casefold-1.0.1-py2.py3-none-any.whl
Collecting regex (from filters->pyota->-r requirements.txt (line 1))
Collecting python-dateutil (from filters->pyota->-r requirements.txt (line 1))
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting class-registry (from filters->pyota->-r requirements.txt (line 1))
  Using cached class_registry-2.1.0-py2.py3-none-any.whl
Collecting pytz (from filters->pyota->-r requirements.txt (line 1))
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota->-r requirements.txt (line 1))
Installing collected packages: six, pysha3, typing, idna, urllib3, certifi, chardet, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, requests, py2casefold, regex, python-dateutil, class-registry, pytz, filters, pyota
Successfully installed asn1crypto-0.23.0 certifi-2017.11.5 cffi-1.11.2 chardet-3.0.4 class-registry-2.1.0 cryptography-2.1.4 enum34-1.1.6 filters-1.3.2 idna-2.6 ipaddress-1.0.18 py2casefold-1.0.1 pyOpenSSL-17.5.0 pycparser-2.18 pyota-2.0.2 pysha3-1.0.2 python-dateutil-2.6.1 pytz-2017.3 regex-2017.12.5 requests-2.18.4 six-1.11.0 typing-3.6.2 urllib3-1.22
Segmentation fault (core dumped)
`

**Comment by iceguru** [comment]
Check the end of the install...

**Comment by bahamapascal** [comment]
Never had that error before, but apparently that is if something is wrong with your Python installation:
https://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped

**Comment by iceguru** [comment]
Think I found the issue...feel like an idiot if it is but sharing for other idiots.

I'm using a live ubuntu USB because I pooched my main distro and I'm too lazy to fix. AKA no updates.

**Comment by bahamapascal** [comment]
Ahhh okay, that would do it I guess. Glad you found the error

**Comment by iceguru** [comment]
I actually didn't. 

I decided just to toss up an amazon cloud service I hadn't used..

**Comment by bahamapascal** [comment]
Ohh okay. But as long as you got it working that's great!
I will close this issue now then :)
